functional:
  - Приложение должно поддерживать язык программирования Python
  - Приложение должно поддерживать язык программирования PHP
  - Приложение должно поддерживать язык программирования Java
  - Приложение должно поддерживать язык программирования С++
  - Приложение должно иметь функцию регистрации
  - Приложение должно иметь внукцию входа
  - Приложение должно иметь возможность начать игру
  - Приложение должно хранить информацию об успехах пользователя
non-functional:
  - Приложение должно быть удобным в использовании
  - Приложение должно быть оптимизировано для скорости работы
  - Приложение должно быть протестировано на совместимость с последними версиями браузеров
  - Приложение должно быть удобным на мобильном устройстве
  - Приложение должно быть способено обрабатывать большое количество трафика
implicit:
